const memory = [
  {
    id: "1",
    timestamp: Date.now() - 5000,
    query: "Why is MongoDB not connecting?",
    text: "MongoDB not connecting",
    resolvedBy: "local",
    tokens: 12,
    entities: ["MongoDB", "connection", "database"],
    embedding: [0.12, -0.88, 0.45]
  },
  {
    id: "2",
    timestamp: Date.now() - 4000,
    query: "I tried restarting server but issue persists",
    text: "Tried restarting server",
    resolvedBy: "local",
    tokens: 10,
    entities: ["server", "restart"],
    embedding: [0.11, -0.87, 0.44]  
  },
  {
    id: "3",
    timestamp: Date.now() - 3000,
    query: "Still getting timeout error in API",
    text: "Still timeout error",
    resolvedBy: "cloud",
    tokens: 11,
    entities: ["timeout", "API", "error"],
    embedding: [0.1, -0.86, 0.46]
  },
  {
    id: "4",
    timestamp: Date.now() - 2000,
    query: "How to center a div using flexbox?",
    text: "CSS flexbox center div",
    resolvedBy: "local",
    tokens: 9,
    entities: ["CSS", "flexbox", "UI"],
    embedding: [0.9, 0.1, -0.3]
  }
];

function cosineSimilarity(a, b) {
  if (a.length !== b.length) {
    throw new Error("Embedding dimensions do not match");
  }
  
  let dot = 0;
  let normA = 0;
  let normB = 0;
  
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  
  if (normA === 0 || normB === 0) return 0;
  
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}



/**
 * Perform semantic similarity search
 * 
 * @param {Array} memory - Array of objects { text, embedding }
 * @param {Array} queryEmbedding - embedding of incoming query
 * @param {number} topK - number of results to return
 * @param {number} threshold - minimum similarity score (optional)
 * 
 * @returns {Array} top matching results
*/
function semanticSearch(memory, queryEmbedding, topK = 5, threshold = 0.5) {
  const results = [];

  for (const item of memory) {
    if (!item.embedding) continue;

    const score = cosineSimilarity(queryEmbedding, item.embedding);

    if (score >= threshold) {
      results.push({
        ...item,
        score, // attach similarity score
      });
    }
  }

  results.sort((a, b) => b.score - a.score);

  return results.slice(0, topK);
}

const queryEmbedding = [0.1, -0.87, 0.48];




function compactTurns(turns, threshold = 0.85) {
  if (!turns || turns.length === 0) return [];

  const compacted = [];

  let currentGroup = [turns[0]];
  let centroid = [...turns[0].embedding]; // initial centroid
  let groupSize = 1;

  for (let i = 1; i < turns.length; i++) {
    const curr = turns[i];

    const score = cosineSimilarity(centroid, curr.embedding);

    if (score >= threshold) {
      
      currentGroup.push(curr);
      centroid = updateCentroid(centroid, curr.embedding, groupSize);
      groupSize++;

    } else {
      // Flush previous group
      compacted.push(mergeGroup(currentGroup));

      // Start new group
      currentGroup = [curr];
      centroid = [...curr.embedding];
      groupSize = 1;
    }
  }

  // Flush last group
  if (currentGroup.length > 0) {
    compacted.push(mergeGroup(currentGroup));
  }

  return compacted;
}



function updateCentroid(oldCentroid, newEmbedding, size) {
  const newCentroid = [];

  for (let i = 0; i < oldCentroid.length; i++) {
    newCentroid[i] =
      (oldCentroid[i] * size + newEmbedding[i]) / (size + 1);
  }

  return newCentroid;
}


// Merge logic 
function mergeGroup(group) {
  if (group.length === 1) {
    return {
      type: "single",
      text: group[0].text,
      original: group,
    };
  }

  return {
    type: "merged",
    text: group.map(item => item.text).join("\n"),
    original: group,
  };
}



function estimateTokens(text) {
  // Rough rule: 1 token ≈ 4 chars (works okay)
  return Math.ceil(text.length / 4);
}

//main function that we will call 
//input is memory
//embedding will generated by ollama api
//maxToken can be dynamic
export function allocateTokenBudget(memory, queryEmbedding, maxTokens = 1200) {

  const relevant = semanticSearch(memory, queryEmbedding, 10, 0.3);

  relevant.sort((a, b) => a.timestamp - b.timestamp);

  const compacted = compactTurns(relevant);

  const scored = compacted.map(turn => {
    const timestamp = turn.original[0].timestamp;

    const age = Date.now() - timestamp;
    const recencyWeight = 1 / (1 + age / 100000);

    const baseScore = turn.original.reduce((acc, t) => acc + (t.score || 0), 0) / turn.original.length;

    const finalScore = baseScore * recencyWeight;

    return {
      ...turn,
      timestamp,
      finalScore,
      tokens: estimateTokens(turn.text),
    };
  });

  scored.sort((a, b) => b.finalScore - a.finalScore);

  const selected = [];
  let usedTokens = 0;

  for (const turn of scored) {
    if (usedTokens + turn.tokens > maxTokens) continue;

    selected.push(turn);
    usedTokens += turn.tokens;
  }

  selected.sort((a, b) => a.timestamp - b.timestamp);

  const context = selected.map(t => t.text).join("\n");

  const finalContext = `
You are given previous conversation context for reference.

IMPORTANT:
- Do NOT treat this as the current user query
- Do NOT respond to this context directly
- Use it only to improve your answer

--- CONTEXT START ---
${context}
--- CONTEXT END ---
`;

  return {
    finalContext,
    usedTokens,
    selected
  };
}

//calling here
// const budget = allocateTokenBudget(memory,queryEmbedding);
// console.log("budget response : ");
// console.log(budget);

//flow
// memory
//   ↓
// semantic search (relevance)
//   ↓
// sort by time
//   ↓
// centroid compaction (merge similar)
//   ↓
// scoring (similarity + recency)
//   ↓
// token budget packing
//   ↓
// chronological reorder
//   ↓
// FINAL CONTEXT